---
title: "Using spike-and-slab joint graphical lasso"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Using spike-and-slab joint graphical lasso}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(spikeyglass)
data("simdat")
```

```{r}
# TODO visualizations of simdat 
# TODO summarize SIMDAT
# TODO FGL
```

The simulated data has 50 variables, and for the three groups there are some common graph structure with blocks of 5 variables being removed in the 2nd and 3rd group - see below. 

```{r}
heatmap(simdat$g[[1]], Rowv = NA, Colv = NA)
heatmap(simdat$g[[2]], Rowv = NA, Colv = NA)
heatmap(simdat$g[[3]], Rowv = NA, Colv = NA)
```



```{r}
## Fig SSJGL
set.seed(1219)
G <- 3
p <- 50
penalty <- "fused"
lam1 <- 1
lam2 <- 1
v1 <- 1
lam.eff <- lam1 + c(1:10) * 5
v0s <- lam1/lam.eff
g <- simdat$g

# takes 4 minutes to run the below
fit1 = ssjgl(Y=simdat$Y,penalty=penalty,lambda0=1, lambda1=lam1,lambda2=lam2, v1 = v1, v0s = v0s, tol.em=1E-4, a=1, b=p, doubly=TRUE, normalize=TRUE)
# 
# 
# 
# # saving since it takes long
# save(fit1, file = here::here("data/fit1.Rdata"))

# load(here::here("data/fit1.Rdata"))

# Get plot titles 
mains <- c(paste0("Class 1"), 
		   paste0("Class 2"), 
		   paste0("Class 3"))


plot_path(lam1/v0s, fit1, thres = 0, normalize = F, xlab = expression(lambda[1]/v[0]^2), ylab = "Partial correlations",  main = mains, par = c(1, 3))


```

```{r include = FALSE}
## Calculate metrics for SSJGL
# fit1$nedges <- fit1$SSE <- fit1$fp <- fit1$tp <- fit1$fn <- fit1$tn <- fit1$dKL <- fit1$L1 <- matrix(NA, length(lam.eff), G)
# fit1$tp.gdiff <- fit1$fp.gdiff <- fit1$fn.gdiff <- rep(NA, length(lam.eff))
# fit1$tp.diff <- fit1$fp.diff <- fit1$fn.diff <- rep(NA, length(lam.eff))
# for(i in 1:length(v0s)){
# 	for(k in 1:G){
# 		met <- getmetric(est=fit1$thetalist[[i]][[k]], truth=Theta[[k]], graph=g[[k]])
# 		fit1$nedges[i,k] <- met$nedges
# 		fit1$SSE[i,k] <- met$SSE
# 		fit1$fp[i,k] <- met$fp
# 		fit1$tp[i,k] <- met$tp
# 		fit1$fn[i,k] <- met$fn
# 		fit1$tn[i,k] <- met$tn
# 		fit1$dKL[i,k] <- met$dKL
# 		fit1$L1[i,k] <- met$L1
# 	}
# 	met2 <- getdiffmetric(est=fit1$thetalist[[i]], truth = Theta, graph=g, tol=1e-2)
# 	fit1$tp.gdiff[i] <- met2$tp.gdiff
# 	fit1$fp.gdiff[i] <- met2$fp.gdiff
# 	fit1$fn.gdiff[i] <- met2$fn.gdiff
# 	fit1$tp.diff[i] <- met2$tp.diff
# 	fit1$fp.diff[i] <- met2$fp.diff
# 	fit1$fn.diff[i] <- met2$fn.diff
# 	cat(".")
# }

```

