// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// admm_iters_adaptive_cpp
List admm_iters_adaptive_cpp(List Y_list, arma::mat lam1, arma::mat lam2, std::string penalty, double rho, double rho_increment, NumericVector weights, int maxiter, double tol, Nullable<List> warm_list);
RcppExport SEXP _spikeyglass_admm_iters_adaptive_cpp(SEXP Y_listSEXP, SEXP lam1SEXP, SEXP lam2SEXP, SEXP penaltySEXP, SEXP rhoSEXP, SEXP rho_incrementSEXP, SEXP weightsSEXP, SEXP maxiterSEXP, SEXP tolSEXP, SEXP warm_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type Y_list(Y_listSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type lam1(lam1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type lam2(lam2SEXP);
    Rcpp::traits::input_parameter< std::string >::type penalty(penaltySEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type rho_increment(rho_incrementSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< Nullable<List> >::type warm_list(warm_listSEXP);
    rcpp_result_gen = Rcpp::wrap(admm_iters_adaptive_cpp(Y_list, lam1, lam2, penalty, rho, rho_increment, weights, maxiter, tol, warm_list));
    return rcpp_result_gen;
END_RCPP
}
// ssjgl_em_inner_cpp
List ssjgl_em_inner_cpp(List S_list, Nullable<List> addvar_list, NumericVector n_vec, List theta_init, std::string penalty, double lambda0, double lambda1, double lambda2, double v0, double v1, bool doubly, double rho, double a, double b, int maxitr_em, double tol_em, int maxitr_jgl, double tol_jgl, double truncate);
RcppExport SEXP _spikeyglass_ssjgl_em_inner_cpp(SEXP S_listSEXP, SEXP addvar_listSEXP, SEXP n_vecSEXP, SEXP theta_initSEXP, SEXP penaltySEXP, SEXP lambda0SEXP, SEXP lambda1SEXP, SEXP lambda2SEXP, SEXP v0SEXP, SEXP v1SEXP, SEXP doublySEXP, SEXP rhoSEXP, SEXP aSEXP, SEXP bSEXP, SEXP maxitr_emSEXP, SEXP tol_emSEXP, SEXP maxitr_jglSEXP, SEXP tol_jglSEXP, SEXP truncateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type S_list(S_listSEXP);
    Rcpp::traits::input_parameter< Nullable<List> >::type addvar_list(addvar_listSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type n_vec(n_vecSEXP);
    Rcpp::traits::input_parameter< List >::type theta_init(theta_initSEXP);
    Rcpp::traits::input_parameter< std::string >::type penalty(penaltySEXP);
    Rcpp::traits::input_parameter< double >::type lambda0(lambda0SEXP);
    Rcpp::traits::input_parameter< double >::type lambda1(lambda1SEXP);
    Rcpp::traits::input_parameter< double >::type lambda2(lambda2SEXP);
    Rcpp::traits::input_parameter< double >::type v0(v0SEXP);
    Rcpp::traits::input_parameter< double >::type v1(v1SEXP);
    Rcpp::traits::input_parameter< bool >::type doubly(doublySEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type maxitr_em(maxitr_emSEXP);
    Rcpp::traits::input_parameter< double >::type tol_em(tol_emSEXP);
    Rcpp::traits::input_parameter< int >::type maxitr_jgl(maxitr_jglSEXP);
    Rcpp::traits::input_parameter< double >::type tol_jgl(tol_jglSEXP);
    Rcpp::traits::input_parameter< double >::type truncate(truncateSEXP);
    rcpp_result_gen = Rcpp::wrap(ssjgl_em_inner_cpp(S_list, addvar_list, n_vec, theta_init, penalty, lambda0, lambda1, lambda2, v0, v1, doubly, rho, a, b, maxitr_em, tol_em, maxitr_jgl, tol_jgl, truncate));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_spikeyglass_admm_iters_adaptive_cpp", (DL_FUNC) &_spikeyglass_admm_iters_adaptive_cpp, 10},
    {"_spikeyglass_ssjgl_em_inner_cpp", (DL_FUNC) &_spikeyglass_ssjgl_em_inner_cpp, 19},
    {NULL, NULL, 0}
};

RcppExport void R_init_spikeyglass(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
