# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' ADMM iterations with adaptive penalties (C++ implementation)
#'
#' @param Y_list List of K data matrices (n_k x p)
#' @param lam1 Matrix-valued lambda1 penalty (p x p)
#' @param lam2 Matrix-valued lambda2 penalty (p x p)
#' @param penalty String: "fused" or "group"
#' @param rho ADMM step size
#' @param rho_increment Multiplicative rho update factor
#' @param weights Numeric vector of length K (sample sizes)
#' @param maxiter Maximum ADMM iterations
#' @param tol Convergence tolerance
#' @param warm_list Optional list of K warm-start precision matrices (or R_NilValue)
#' @return List with theta (list of K matrices), Z (list of K matrices), diff, iters
#' @keywords internal
admm_iters_adaptive_cpp <- function(Y_list, lam1, lam2, penalty, rho, rho_increment, weights, maxiter, tol, warm_list = NULL) {
    .Call(`_spikeyglass_admm_iters_adaptive_cpp`, Y_list, lam1, lam2, penalty, rho, rho_increment, weights, maxiter, tol, warm_list)
}

#' Full EM inner loop in C++ (E-step + block detection + ADMM)
#'
#' Runs the EM algorithm for a single v0 step entirely in C++, avoiding
#' R overhead between iterations. Handles block decomposition via connected
#' components (replacing igraph), precomputes covariance once, and runs
#' the ADMM solver per block.
#'
#' @param S_list List of K sample covariance matrices (p x p, biased)
#' @param addvar_list List of K addvar matrices for imputation (or NULL)
#' @param n_vec Numeric vector of sample sizes (length K)
#' @param theta_init List of K initial precision matrices
#' @param penalty String: "fused" or "group"
#' @param lambda0 Scalar diagonal penalty
#' @param lambda1 Scalar off-diagonal penalty
#' @param lambda2 Scalar cross-group penalty
#' @param v0 Spike variance for this step
#' @param v1 Slab variance
#' @param doubly Logical: use doubly spike-and-slab?
#' @param rho ADMM step size
#' @param a Beta prior shape1
#' @param b Beta prior shape2
#' @param maxitr_em Max EM iterations
#' @param tol_em EM convergence tolerance
#' @param maxitr_jgl Max ADMM iterations
#' @param tol_jgl ADMM convergence tolerance
#' @param truncate Threshold for zeroing small entries
#' @return List with theta, prob1, prob2, d1, d2, pi_delta, pi_xi, itr
#' @keywords internal
ssjgl_em_inner_cpp <- function(S_list, addvar_list, n_vec, theta_init, penalty, lambda0, lambda1, lambda2, v0, v1, doubly, rho, a, b, maxitr_em, tol_em, maxitr_jgl, tol_jgl, truncate) {
    .Call(`_spikeyglass_ssjgl_em_inner_cpp`, S_list, addvar_list, n_vec, theta_init, penalty, lambda0, lambda1, lambda2, v0, v1, doubly, rho, a, b, maxitr_em, tol_em, maxitr_jgl, tol_jgl, truncate)
}

